### ISSUE TITLE
Provisioning - how to use?

### ISSUE THREAD

**Issue by arheom** [SharePoint/PnP-JS-Core#169]
#### Category

[ ] Enhancement

[ ] Bug

[X] Question
#### Provisioning more info

I am trying to find more information about provisioning functionality. Is there a documentation or something I can dig into to be able to use it? I see I should send a file template in json (applyTemplate function) with the configuration. Is there an already made template I could have a look?

Thanks a lot!
Bogdan

**Comment by mauricionr** [comment]
@arheom I'm trying to undestand about provisioning

https://msdn.microsoft.com/en-us/pnp_articles/branding-and-site-provisioning-solutions-for-sharepoint

https://msdn.microsoft.com/en-us/pnp_articles/pnp-remote-provisioning

**Comment by patrick-rodgers** [comment]
Hi Bogdan,

The provisioning functionality is not as full as with the pnp CSOM remote provisioning library - but there are some methods there. Honestly we likely need to review it as there have been significant updates to the CSOM core which are not reflected here. I am not sure if the pnp templates currently work or not. We discussed this on the last weekly call in fact. Actively looking for someone to pick up and run with provisioning if there is sufficient interest. It is definitely an area where we can invest more time as a community.

**Comment by koltyakov** [comment]
Also interested in some additional information and examples about this.

**Comment by arheom** [comment]
Hi Patrick (@patrick-rodgers),

I could also work a bit on the provisioning part. I need to implement anyhow for the project I am working now some site columns, site content type and web provisioning, so better to have it in the pnp. Do you have some starting kit for the provisioning part (to import some code from the CSOM project?)? 

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @arheom,

I don't have a starter kit or anything. What is there was contributed early on in the project and hasn't really been updated. There would be two ways to approach provisioning in js core:

- Take what is there now and begin modifying it.
- Start fresh and design around processing the templates used by CSOM engine

Personally I would like to ensure that IF we are going to embark on trying to include provisioning in JavaScript we are able to process the same templates as the core CSOM provisioning. I don't see real value in having two systems, especially as the CSOM provisioning is fairly mature at this point. Now, I wouldn't expect we could support everything immediately, but that is where I'd like to see us start. I think it makes sense to model the provisioning after the CSOM since we would be processing the same templates. We would also keep it "built" into separate files as many folks may not need it and it wouldn't really be appropriate for use in the browser.

Also, would want to stress that this is something to be run from node and not in the browser, but I see a lot of value in supporting the ability to have a provisioning service run in node.

One issue is that provisioning is big and complicated - and has been successful because for the CSOM we had several community members really step up and own it. Would need a similar few folks to essentially own it for the js library as well. That being said it would be a HUGE contribution and provide great community visibility as well as a deeper involvement with the PnP Core team for anyone willing to put in the time.

**Comment by arheom** [comment]
Hi @patrick-rodgers,

Thanks for the info! I did a mix between those for now (we still need to implement this into a running project, so cannot do it now from scratch...would need discussions about architecture, re-design...which will take time). So I used the same architecture like the current solution, but got all the code from the CSOM repository and transformed it into JSOM (with some exceptions, where in JSOM could not be done, like creating a content type with a specific ID, needs to be done with a parent id...). There are some things I didnt manage to do, like creating document sets (I will research this topic later), but I will come back later to them. For now I have implemented the content type and site fields part in this way and I am testing them now. Once I am done with testing and looks good, I can create a publish branch / pull request for you to have a look.

**Comment by bernd7636** [comment]
Hello!
Is there any progress about the JSOM provisioning engine? I still can only find the "applyTemplate" function (https://github.com/SharePoint/PnP-JS-Core/blob/69a38f8/src/sharepoint/provisioning/provisioning.ts#L48) in the library. How can I create a JSON template (with Pnp JS)? Or is there a way to use Pnp PowerShell to create a suitable JSON template?
Thanks in advance!
Bernd

**Comment by patrick-rodgers** [comment]
@bernd7636 - no, as I said above if there is interest from the community to expand this capability would be looking for one or more folks to step up and own it. Building out provisioning in js core is not currently a priority for the core team - but we would absolutely accept PRs. Recommendation would be to use the provisioning in the CSOM core and PowerShell as they are both more feature rich and better supported through examples and community contribution.

**Comment by mauricionr** [comment]
@patrick-rodgers as i saw in the last bi-weekly the provisioning is not part of this library(removed), right?

Thanks!

**Comment by patrick-rodgers** [comment]
@mauricionr - yes that is correct. We will be removing provisioning from this library with the upcoming release of 2.0 - but we will be moving it to another repo so it can be managed as a separate project. As part of that we will be looking for folks from the community to "take ownership" and drive the growth of the provisioning code. Thanks!

**Comment by olemp** [comment]
@patrick-rodgers I will have a look at the provisioning in the beginning of 2017. Will look into documentation.

**Comment by olemp** [comment]
@patrick-rodgers We (my company) have a product/solution which is built on a WSP Web Template today. We want this to use client side provisioning, so during this transition, I'll be doing some work on making the provisioning code solid.

Not all customers have the budget for site collection provisioning, and for some subsites is more than enough.

**Comment by olemp** [comment]
@arheom The provisioning code is a port from https://github.com/Puzzlepart/js-sites-core which has been used for several customer projects.

Here's a full sample:
https://github.com/Puzzlepart/js-sites-core/blob/master/samples/Full-Sample.md

**Comment by arheom** [comment]
I just seen the provisioning is out from dev branch. Is there a place where was added? I have implemented the site fields, content types and token parser from .NET provisioning and wanted to create a PR.

**Comment by patrick-rodgers** [comment]
Yes, as discussed in a few of the recent calls we are removing provisioning from this library and will be moving it to [its own repo](https://github.com/SharePoint/pnp-js-provisioning). That is on my todo list and will happen before the 2.0.0 release it is just a matter of finding the time.

**Comment by patrick-rodgers** [comment]
Closing this issue, please see the refactored provisioning code at the [new repo](https://github.com/SharePoint/pnp-js-provisioning). It is def a work in progress but now works in node!
