### ISSUE TITLE
Adding multiple itens, saving last object in the context for all add's

### ISSUE THREAD

**Issue by mauricionr** [SharePoint/PnP-JS-Core#285]
#### Category
[x] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Use each object passed in add method

#### Observed Behavior
For each object  i change the `task.DataObrigacoes`, and pass to add method, but is
Saving the last object passed to add method for each post request

I've tried use Batch but still with the same behavior

#### Steps to Reproduce
While looping checking if date target is before or same as final date.(i hope the image could help)

![image](https://cloud.githubusercontent.com/assets/2263551/21619129/809fb608-d1d5-11e6-989c-2cd0818c9603.png)

Thanks!

**Comment by patrick-rodgers** [comment]
Try this:

```
    pnp.sp.web.lists.ensure("rapidadd").then(listresult => {

        let items = listresult.list.items;

        for(let i = 0; i < 5; i++) {
            items.add({
                Title: `Item - ${pnp.util.getRandomString(5)}`
            });
        }
    });
```

**Comment by mauricionr** [comment]
hey @patrick-rodgers i got the same issue

![image](https://cloud.githubusercontent.com/assets/2263551/21625088/1dbd55b0-d1f1-11e6-8e0f-43292a62919d.png)

![image](https://cloud.githubusercontent.com/assets/2263551/21625242/e1708676-d1f1-11e6-9e58-da00eb8eda31.png)

ẁhen getAs is resolved inside add method, the properties is always de last properties received, adding always the same object

```typescript
parentList.select("ListItemEntityTypeFullName").getAs
```

```typescript
public add(properties: TypedHash<any> = {}): Promise<ItemAddResult> {

        let removeDependency = this.addBatchDependency();

        let parentList = this.getParent(QueryableInstance);

        return parentList.select("ListItemEntityTypeFullName").getAs<{ ListItemEntityTypeFullName: string }>().then((d) => {

            let postBody = JSON.stringify(Util.extend({
                "__metadata": { "type": d.ListItemEntityTypeFullName },
            }, properties));

            let promise = this.postAs<{ Id: number }>({ body: postBody }).then((data) => {
                return {
                    data: data,
                    item: this.getById(data.Id),
                };
            });

            removeDependency();

            return promise;
        });
    }
```

Thansk!

**Comment by patrick-rodgers** [comment]
When I tested the code I pasted above I got 5 items with different titles. The properties will be maintained across the getAs because they are being passed into the function and are part of the closure. So I don't think that is the problem. If you run that example code does it create unique items for you?

Your second question - why do we have to do that each time - is simplicity. We have to have that value for updating and adding items and instead of trying to cache it or maintain that value I just have the code grab per request. In cases where you are adding many items to the same list this would not be the most efficient way to handle it - but for the general case I think it is best.

It sounds like you are looking for the optimal way to add a lot of items to a single list? Can you add them all at once - or do you need to add them sequentially? i.e. if we were to do something which of the two method pseudo signatures is closest to what you are trying to do:

`addMany(items: any[])`

or
// existing method with extra param
```
// get the ListItemEntityTypeFullName yourself and pass it so the method doesn't need to look it up.
add(item, ListItemEntityTypeFullName)
```

**Comment by mauricionr** [comment]
hey @patrick-rodgers, in my case i need `addMany(items: any[])`

Thanks!

**Comment by mauricionr** [comment]
@patrick-rodgers assign a new object to task solve my problem adding multiple items in a loop with different target dates for each item.

```javascript
task = Object.assign({}, task);                    
promises.push(items.add(task))
```
