### ISSUE TITLE
Requirement to use "pnp.sp.web" when we try to use pnp.sp.web within the custom page of either "pages" or "site pages" library.  

### ISSUE THREAD

**Issue by rajusdp** [SharePoint/PnP-JS-Core#353]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement
Requirement to use "pnp.sp.web" when we try to use pnp.sp.web within the custom page of either "pages" or "site pages" library.  

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
I am trying to build a single page app, Best way is to start with the blank aspx custom page under pages or site pages library, I was expecting that when i start using pnp.sp.web.lists it will fetch the web/lists object based on the page context, however it throws the error.. "GET https://domainname.sharepoint.com/sites/dev/Pages/_api/web/lists 404 (Not Found)" 

#### Observed Behavior
mentioned the expected behavior above

#### Steps to Reproduce
> Include the generated output  .js file in the https://domainname.sharepoint.com/sites/dev/Pages/xyz.aspx and then try to open the page.
> Check the debug console 

Thanks!
Raj.

**Comment by patrick-rodgers** [comment]
Can you check to see if the page you created has the _spPageContextInfo global variable available. I am asking because that is how we determine the url, but if you are uploading an empty aspx page you created that doesn't have the OOTB SharePoint masterpage / controls it might be missing. If it is not there you will need to either create your objects directly:

```TypeScript
let w = new Web("My url");
```

or use the setup's [baseurl property](https://github.com/SharePoint/PnP-JS-Core/wiki/Configuration#base-url) to set the root url of the app.

**Comment by rajusdp** [comment]
Hi Patrick,
thank you for your quick reply, 
Yes i am creating a blank page and hence it misses _spPageContextInfo global variable, I am currently using "Const w = new Web('My url')". 

However,since my application is more generic(not specific) it requires me to pick from the context of the page, I am currently trying to use the method "getWebUrlFromPageUrl" with "window.location.href" as a parameter. I am looking for more robust in built method if there is any.

Thanks,
Raj.

**Comment by patrick-rodgers** [comment]
Would leave that up to you how you want to provide the url. Since you are working outside the context of the classic page we can't pick it up. This is inline with what we now do for SharePoint framework requiring the context be added. I recommend either hard coding it per-deployment or arriving at another method then supply it to the library using the baseUrl setup parameter (or the Web object directly as you are doing).

**Comment by rajusdp** [comment]
Sure Patrick Thank you for looking at my request and for the suggestion.
