### ISSUE TITLE
How to add the sort properties in (SortList)

### ISSUE THREAD

**Issue by LMahfoud** [SharePoint/PnP-JS-Core#364]
I try to sort the result in many ways, sadly it's give the error (Bad request : 400 )

SortList: ["'Title':'Descending'"]
SortList: ["Title:Descending"]
SortList: ["Title Descending"]
SortList: ["{'Property':'Title', 'Direction': 'Descending'}"]

Please can you give the correct syntax to make it, and wherer can i find the full documentation for pnp.js

Thank you all

**Comment by patrick-rodgers** [comment]
Hi @LMahfoud - mentioned in [this thread](https://github.com/SharePoint/PnP-JS-Core/issues/335) title isn't sortable by default. The correct syntax is:

```
SortList:
  [
    {
      Property: 'Title',
      Direction: SortDirection.Ascending
    }
  ]
```

Our docs are in the [wiki](https://github.com/SharePoint/PnP-JS-Core/wiki) and you can see the [developer guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) as a starting point. We don't yet have everything documented due to time, but certainly welcome contributions to the wiki to help get things updated.

**Comment by LMahfoud** [comment]
Sound good, thank you

**Comment by patrick-rodgers** [comment]
Going to close this as it seems to be answered. Please reopen if this is not the case. Thanks for your interest in sp-pnp-js!
