### ISSUE TITLE
Batch not work for ensureuser api

### ISSUE THREAD

**Issue by JackHu88** [SharePoint/PnP-JS-Core#380]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Batch not work for ensureuser api

#### Observed Behavior
I want add many users to a site, so i running the code below to test it, but when i check the request header, the ensureuser api was requested 3 times not processed in a batch.

#### Steps to Reproduce
```
var batch = $pnp.sp.web.createBatch();

$pnp.sp.web.inBatch(batch).ensureUser("jhu1@xxx.com").then(function (user){
    var userId= user.Id;	
    console.log(userId);
})
$pnp.sp.web.inBatch(batch).ensureUser("jhu2@xxx.com").then(function (user){
    var userId= user.Id;	
    console.log(userId);
})
$pnp.sp.web.inBatch(batch).ensureUser("jhu3@xxx.com").then(function (user){
    var userId= user.Id;	
    console.log(userId);
})

batch.execute().then(d => console.log("Done"));
```

![a65917ee-0b1f-11e7-925b-c36f02f621ac](https://cloud.githubusercontent.com/assets/26239484/24128686/79b8279c-0e18-11e7-9c01-5d84532f31b6.png)

**Comment by patrick-rodgers** [comment]
Thanks, will have a look at this.

**Comment by patrick-rodgers** [comment]
Fixed this. Root cause was a change in behavior a few releases ago where we stopped copying the batch to child objects through the constructor. So for those methods (including ensureUser) where we create a new Web instance to avoid altering the current _this_ we needed to set the batch on that new instance.

Specifically for ensureUser I also took a look at the return and it contains the full user information - so I updated the method to return the below interface:

```TypeScript
export interface WebEnsureUserResult {
    data: any;
    user: SiteUser;
}
```

And to simplify things I added an interface defining the properties that come back from the basic call for a user:

```TypeScript
export interface SiteUserProps {
    Email: string;
    Id: number;
    IsHiddenInUI: boolean;
    IsShareByEmailGuestUser: boolean;
    IsSiteAdmin: boolean;
    LoginName: string;
    PrincipalType: number;
    Title: string;
}
```

Sample usage:

```TypeScript
    const batch = pnp.sp.createBatch();

    pnp.sp.web.inBatch(batch).ensureUser("i:0#.f|membership|...").then(r => {

        // you can directly query the user
        r.user.select("LoginName").get().then(u => { console.log(`Here is that value: ${u.LoginName}`); })

    });

    pnp.sp.web.inBatch(batch).ensureUser("i:0#.f|membership|...").then(r => {

        console.log(r.data.Id);

    });

    batch.execute().then(_ => console.log("batch done."));
```

Meaning the method now returns the raw data for that user on the data property and a queryable representing that user in the user property of the return. Should save some requests and is inline with what we do for other similar operations. Will be merging this into dev shortly. Thanks for reporting it!

**Comment by patrick-rodgers** [comment]
Reopening this as it affects all methods that "clone" the object to do a request in the method body. Working to fix everything now, but wanted to track it correctly.

**Comment by patrick-rodgers** [comment]
Now closing as properly fixed for all affected methods in #382

**Comment by JackHu88** [comment]
Hi @patrick-rodgers , I'm new to npm, opening the PnP-JS-Core-dev project in Visual Studio Code, could you please guide me how to rebuild it then generate the pnp.js?

**Comment by patrick-rodgers** [comment]
@JackHu88 - you can [follow the steps in this wiki article](https://github.com/SharePoint/PnP-JS-Core/wiki/Getting-Started:-Contribute) to get started. Currently I think you need to do the npm install step. Then you'll want [gulp package](https://github.com/SharePoint/PnP-JS-Core/wiki/Gulp-Tasks#package). After that the pnp.js files will be in the dist folder.

**Comment by JackHu88** [comment]
Thanks @patrick-rodgers , i got the pnp.js now.

**Comment by JackHu88** [comment]
Hi @patrick-rodgers , could you pls help to have a look this issue?

**Comment by patrick-rodgers** [comment]
@JackHu88 - please reopen issues so they are visible to folks trying to help. I am reasonably sure this is fixed - just confirmed again as well. So you might not have the latest code when you built the dev branch.

**Comment by JackHu88** [comment]
I tried with the latest code, it can works now, thx.
