### ISSUE TITLE
Support for generic types with PnpClientStore

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#390]
#### Category
[x] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Objects store in local/session storage via pnp.storage.local/session and retrieved after that, keep their proper type with methods, and complex objects.

#### Observed Behavior
Currently PnpClientStore.get and getOrPut return an any type. That has a lot of impacts on the deserialization process.
https://www.typescriptlang.org/docs/handbook/generics.html 

#### Steps to Reproduce
Store an object of a certain type (not any or object), retrieve it, you just lost complex types and methods associated.

EDIT1: after submitting I went to see the code, I think it's a bug and the interface is not properly declared https://github.com/SharePoint/PnP-JS-Core/blob/master/src/utils/storage.ts#L170

EDIT2: after investigating I think this is also related to the way objects are implemented and casted
http://stackoverflow.com/a/39423567/3808675
should implement that recursively 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
instead of that 
https://github.com/SharePoint/PnP-JS-Core/blob/master/src/utils/storage.ts#L50

**Comment by patrick-rodgers** [comment]
Can you provide a code snippet that shows this? Typically when storing things you would store as little as possible and support a rehydrate method (object.FromString for example). Happy to have a look but want to make sure we are looking at the right thing. Thanks!

**Comment by baywet** [comment]
Sure, sorry for not providing it at first
```
import * as moment from 'moment'

import pnp from "sp-pnp-js"
export class Service {
    public retrieve(): Promise<Array<EventPage>> {
        return pnp.storage.local.getOrPut("somekey", () => {
            let values = new Array<EventPage>();
            values.push(new EventPage("title1", "division1", new Date(), "paris", "http://dev.office.com", new Date()));
            values[0].getEventDate("MM/DD/YYYY"); // works fine (when nothing in local storage)
            return Promise.resolve(values);
        }, pnp.util.dateAdd(new Date(), "minute", 1440))
            .then((values: Array<EventPage>) => {
                console.log("search results" + values.length);
                values[0].getEventDate("MM/DD/YYYY"); // => works when nothing in cache, throws exception 'TypeError: values[0].getEventDate is not a function' when retrieving from cache
                return values;
            });
    }
}
export class EventPage {
    title: string;
    division: string;
    date: Date;
    location: string;
    url: string;
    endDate: Date;

    constructor(title: string, division: string, date: Date, location: string, url: string, endDate: Date) {
        this.title = title;
        this.division = division;
        this.date = date;
        this.location = location;
        this.url = url;
        this.endDate = endDate;
    }

    getEventDate(format: string) {
        return moment(this.date).format(format);
    }

    getEventEndDate(format: string) {
        return moment(this.endDate).format(format);
    }
}
let myService = new Service();
myService.retrieve().then(() => {
    console.log("data retrieved successfully");
});
```

**Comment by patrick-rodgers** [comment]
Thanks, will have a look

**Comment by patrick-rodgers** [comment]
Had a look at this and as well [this thread](https://stackoverflow.com/questions/14027168/how-to-restore-original-object-type-from-json). The real issue is that we don't know how to hydrate your object from T. Once the code is JS it has no meaning.

So we could do something like support a method that takes a factory with an interface to cover all the possible constructors:

```TypeScript

export interface ManyConstructors<T> {
    new (p1?: any, p2?: any, p3?: any, p4?: any, p5?: any, p6?: any, p7?: any, p8?: any): T;
}

    public getAs<T>(factory: ManyConstructors<T>, key: string): T {

        let g = this.get(key);

        if (g !== null) {
            return Util.extend(new factory(), g);
        }

        return <T>g;
    }
```

Problem with that is that we can't know how to hydrate your object. For example the dates in your object come back as strings - we would have to track that and use the date constructor. Same for any other type builtin or otherwise. That's a mess and support nightmare waiting to happen.

I think the best solution is to have your code handle it - then you can cover any case you encounter. Then the question is where to run that code. It needs to be in the get method since we know if we got it out of the cache and you don't. So you'll end up with a calling pattern like this:

```TypeScript
pnp.storage.local.get("somekey", EventPage.Deserializer);
// and
pnp.storage.local.getOrPut("somekey", EventPage.Getter, new Date(), EventPage.Deserializer);

// with an updated EventPage
export class EventPage {
// ...
    public static Getter(): EventPage {

        return new EventPage("title1", "division1", new Date(), "paris", "http://dev.office.com", new Date());
    }

    public static Deserializer(json: any): EventPage {
        return new EventPage(json.title, json.division, new Date(json.date), json.location, json.url, new Date(json.endDate));
    }
}
```

The get isn't too bad but then the getOrPut requires you also set the expiration. Another solution would be to just only write a serialized by you version of your objects and then read a serialized version back and employ a ToProps => json and FromProps(json) method.

Thoughts? I don't think adding a ton of serialization complexity to the library is a great idea because there will always be another case we don't cover.

**Comment by baywet** [comment]
Thanks for investigating. I understand the issue. 
I think the library should provide support for de-/serializer maybe trough an interface instead. This way we could still pass regular object with no crazy prototypes from the get/set/getOrPut methods. If the library detects the interface is implemented, it calls the methods, passing the json when deserializing. 
GetOrPut/Get/Put should also be generic, not leveraging any.
This way the library could implement the interface (let's call it ISerializable?) for it's own classes: right now if I try to cache a search result, for a search based navigation scenario for example, and get from the cache, because the object is complex, it breaks.
With that responsability for serializing/deserializing is left to the consumer of the library but support for it is provided. What do you think?

**Comment by baywet** [comment]
any opinion on that @patrick-rodgers  ??

**Comment by patrick-rodgers** [comment]
I have been thinking about this - but the fundamental issue remains. Once the code is no longer TypeScript the interfaces are gone and have no meaning. It also means we have to wrap all the results that are coming back - [now we just store them](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/caching.ts#L43) since they should just be JSON coming back from the server. I still worry that anything we do won't handle 100% of cases - so I think leaving it as is remains the best option. Then we have whatever limitations come with JSON.* vs. having to support some custom work we did. Put another way - you would face this same issue if you used localStorage directly not through the library so how would you handle it? And extend that to handle generic cases?

If you want to put together a PR that you think solves this, happy to have a look - but for now I think we are good with what we have.

**Comment by baywet** [comment]
Thanks @patrick-rodgers  for your thoughts. I agree it's not an easy one. We discussed about it internally with our team about it and we're currently trying to implement what I suggested on top of the pnp storage lib. So far it's working well, still needs some polishing. Once we have a bit of feedback from QA on that thing and if I get approval from my management I'll try to retro-fit that directly in here. Closing for now.
