### ISSUE TITLE
Partial imports for pnp js

### ISSUE THREAD

**Issue by jquintozamora** [SharePoint/PnP-JS-Core#436]
#### Category
[x ] Enhancement

[ ] Bug

[x ] Question

#### Expected / Desired Behavior / Question
When we only need few speficic methods in our solution (SPFx), could be ideal to load the library partially. Something like:
```js
import { getByTitle } from "sp-pnp-js/lib/lists";
getByTitle("My List").items.get().then((items: any[]) => {
    console.log(items);
});
```
Only loading the specific modules needed for getByTitle. Maybe that could reduce the size of the file quite bit.

#### Observed Behavior
When we use sp-pnp-js library we do import pnp from "sp-pnp-js" which means that bundlers include the whole pnp.js library (which is ~127KB minified).
```js
import pnp from "sp-pnp-js";
pnp.sp.web.lists.getByTitle("My List").items.get().then((items: any[]) => {
    console.log(items);
});
```

Thanks!

**Comment by patrick-rodgers** [comment]
You can already partially import many of the objects.

We will never support importing at the function level because that breaks the library's model. The getByTitle function has no knowledge of the api url parts that come before it, it just appends that part to the query. What you are proposing would require every function to have full knowledge of the api url and need to take additional parameters such as list name. It also eliminates the ability to have composable parts. We would need then to support functions for list fields, content type fields, site fields, etc because they all have different parent paths.

We did try to move the lib folder to es6 modules so that bundlers could only import the parts required, but that turns out to break everything that relies on uglifyjs (which is apparently everything) so we had to go back to es5.

For production I would recommend you don't bundle this library but rather reference it from a CDN as an external. That way clients download it once (127k is not large) and cache it for use across all your components that use it.

**Comment by jquintozamora** [comment]
Thank for your detailed explanation @patrick-rodgers , 
Do you have any code sample using partially imports ? 

Regards!

**Comment by patrick-rodgers** [comment]
There aren't any specific examples for this, but you can see the [usage here](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Webs#get-a-web-directly). Generally the library needs to start with a Web instance to correctly build the query. You can import any of the other objects but you'll need to supply the full url to the constructor.
