### ISSUE TITLE
file.getLimitedWebPartManager() issues

### ISSUE THREAD

**Issue by mstivoi** [SharePoint/PnP-JS-Core#458]
#### Category
[ ] Enhancement

#### Expected / Desired Behavior / Question

WebPartDefinition.SaveWebPartChanges() method does no exists .

**Comment by patrick-rodgers** [comment]
Hi @mstivoi - I've had a look at this and it is easy enough to add that method (as well as the few others that aren't there now). The issue I see is that I can't determine how to actually edit the web part via REST. Meaning update say the title and then save it. Do you have some sample code that shows how you are doing it via REST?

**Comment by mstivoi** [comment]
Hi patrick . I could workaround my issue with running eval(script) from sp.js library . 
This is "CSOM" if server side . Or JSOM if JavaScript.
I don't know how to call SaveWepPartChanges in pure REST. It seems very complicated.

**Comment by patrick-rodgers** [comment]
Ok, I thought you had a way since you requested the method be added. I am not aware of a way to edit web parts via REST. But have added the method you requested which will be in the next release.

There is not support for taxonomy via REST. There are methods to manage workflow associations via rest but we haven't added support to the library as there to date isn't any demand for this.

I am going to close this issue for now as the requested method is added, please reopen or create a new issue to continue the conversation. Thanks!
