### ISSUE TITLE
Is it possible to use pnp-js-core from within an outlook add-in.

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#505]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question
I'd like to create an  outlook add-in that works when a user open an item in the inbox.
It would show user all the items in a sharepoint list that  were created by the sender of the email, and let the user add the email as an attachment tone of those sharepoint listitems.

We use Exchange online and sharepoint online.

What would i need to do to get authenticated to sharepoint?

**Comment by s-KaiNet** [comment]
If you are building SPA application you can use [adal.js](https://github.com/AzureAD/azure-activedirectory-library-for-js) library for that purpose.     

Here is a sample of using adal.js with pure javascript (jquery) spa - [Integrating Azure AD into a single page app](https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi) or [angularjs (1.x) version](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi)
The only difference for you, is that you need to provide required permissions in Azure portal for your app (in order to utilize SharePoint rest api)  and use SharePoint urls instead of custom api (like in the sample).     

There is also a writing from Scrott Hiller about using adal.js (about a bit outdated version of adal.js so don't be confused) - [Calling the Office 365 APIs with jQuery and Adal.js](https://www.itunity.com/article/calling-office-365-apis-jquery-adaljs-2758), anyway concepts are the same. With help of adal.js you are obtaining access token for your azure ad protected resource (SharePoint in your case) and send request to rest api with `Bearer <your SP resource access token>` authorization header.    
Currently you can setup a header with pnp.setup() method

**NOTE:** adal.js has some issues with IE security zones you need to be aware of - please read [this issue](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/102) and [this one](https://github.com/SharePoint/sp-dev-fx-webparts/issues/36)

**Comment by patrick-rodgers** [comment]
This appears to be answered so closing the issue - please _reopen_ if needed. Thanks!

**Comment by russgove** [comment]
thanks Sergei /patrick.
so I managed to get adal.js working in a react outlook addin and I've got the id_token. Is there any plumbing in pnp-js core to work with adal,.js? 
Russell

**Comment by patrick-rodgers** [comment]
No, there is no special plumbing but you can I think set the header and things should work. At least that is my understanding of the flow. Once the next release comes out on Tuesday you can also use the [configure method](https://github.com/SharePoint/PnP-JS-Core/wiki/Configuration#configure-method) to make this a little easier.

**Comment by patrick-rodgers** [comment]
I think is is answered so going to close. Please _reopen_ if needed. Thanks!
