### ISSUE TITLE
Compiling a project with TypeScript >= 2.4.1 causes errors

### ISSUE THREAD

**Issue by tylerjwatson** [SharePoint/PnP-JS-Core#526]
### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.0.6 ]

#### Observed Behavior

Compiling a project with `sp-pnp-js` as an installed module with typescript version >= 2.4.1 results in the following compilation errors:

```
41 export declare class AttachmentFile extends QueryableInstance {
                        ~~~~~~~~~~~~~~

node_modules/sp-pnp-js/lib/sharepoint/attachmentfiles.d.ts(41,22): error TS2415: Class 'AttachmentFile' incorrectly extends base class 'QueryableInstance'.
  Types of property 'delete' are incompatible.
    Type '(eTag?: string) => Promise<void>' is not assignable to type '(deleteOptions?: FetchOptions, parser?: ODataParser<any>) => Promise<any>'.
      Types of parameters 'eTag' and 'deleteOptions' are incompatible.
        Type 'FetchOptions' is not assignable to type 'string'.

63 export declare class File extends QueryableShareableFile {
                        ~~~~

node_modules/sp-pnp-js/lib/sharepoint/files.d.ts(63,22): error TS2415: Class 'File' incorrectly extends base class 'QueryableShareableFile'.
  Types of property 'delete' are incompatible.
    Type '(eTag?: string) => Promise<void>' is not assignable to type '(deleteOptions?: FetchOptions, parser?: ODataParser<any>) => Promise<any>'.
      Types of parameters 'eTag' and 'deleteOptions' are incompatible.
        Type 'FetchOptions' is not assignable to type 'string'.

280 export declare class Version extends QueryableInstance {
                         ~~~~~~~

node_modules/sp-pnp-js/lib/sharepoint/files.d.ts(280,22): error TS2415: Class 'Version' incorrectly extends base class 'QueryableInstance'.
  Types of property 'delete' are incompatible.
    Type '(eTag?: string) => Promise<void>' is not assignable to type '(deleteOptions?: FetchOptions, parser?: ODataParser<any>) => Promise<any>'.
      Types of parameters 'eTag' and 'deleteOptions' are incompatible.
        Type 'FetchOptions' is not assignable to type 'string'.

34 export declare class Folder extends QueryableShareableFolder {
                        ~~~~~~

node_modules/sp-pnp-js/lib/sharepoint/folders.d.ts(34,22): error TS2415: Class 'Folder' incorrectly extends base class 'QueryableShareableFolder'.
  Types of property 'delete' are incompatible.
    Type '(eTag?: string) => Promise<void>' is not assignable to type '(deleteOptions?: FetchOptions, parser?: ODataParser<any>) => Promise<any>'.
      Types of parameters 'eTag' and 'deleteOptions' are incompatible.
        Type 'FetchOptions' is not assignable to type 'string'.

```
The problem can be resolved for us by installing `typescript@2.3.4` so it's not a huge priority, but those who want to use sp-pnp-js in their TypeScript project compiled with 2.4.1 or later will need to install an earlier version of TS.

**Comment by patrick-rodgers** [comment]
Two things on this - 1) TS team decided to make changes that broke existing functionality, something they do fairly regularly. This caught us totally by surprise (learned about it when automated builds started breaking) and we took the step of locking the version in library at 2.3.4. (You can see that on dev branch currently). The changes required for this are fairly substantial and don't add any value - really we are just satisfying some new compiler rules, not gaining any benefit to the library. So that is frustrating from a maintainer standpoint.

2) We need to address it (and will) as we need to work with future versions (and the latest current) of TS - but I am not sure if anything can be done in time for tomorrow's release. The amount of changes, testing, etc is considerable.

For now the work around is to use either a version from CDN (you then don't have to build the library into your project) or to lock on 2.3.4 for now. I get that folks want to use the latest TS and 100% encourage and support that - but it is a time challenge to be forced to rewrite large portions of the library.

Hope that makes sense - it is absolutely something we'll look at but don't have a promise on timing yet.

**Comment by patrick-rodgers** [comment]
So it turns out this was a simpler thing then the error messages would indicate at first look. Have made the necessary updates and merged them to dev. So this will be part of tomorrow's release. Thanks!

**Comment by patrick-rodgers** [comment]
I would support such a discussion, but the folks on that team seem unreceptive to that type of feedback. If nothing else it would be nice to ship these new rules as off by default for a couple versions so people have a chance to adjust without builds failing being the notification.
