### ISSUE TITLE
Expanding recurrent events in Event List

### ISSUE THREAD

**Issue by Jozeevis** [SharePoint/PnP-JS-Core#543]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Question
For a project I am working with Share Point Event lists/Calendars. I recently encountered the problem of recurring events, and how they are saved in Sharepoint.

Is it possible, through pnp, to directly request the expanded list from sharepoint (I saw somewhere this was possible through CAML queries?), or do I have to request the items as is and expand them in my own code?

Any other recommendations to handle this issue would be welcome as well!

**Comment by patrick-rodgers** [comment]
What exactly are you trying to retrieve? You can use CAML queries, though that isn't the recommendation if we can find another way. There is also the expand operator so if you need to expand a related field that often does the trick. Can you share some sample code that isn't working currently? Thanks!

**Comment by koltyakov** [comment]
I assume that @Jozeevis means working with recurrent calendar events as if they were separate items with their own event dates (physically generated from recurrence settings).
I always recommend avoiding recurrent events as possible due to the architecture how they work. Recurrent events mostly useless in client side APIs (REST, JSOM, CSOM). You can only get the initial item(s) with recurrence settings and duplicate recurrence logic on the client. But you can't define filter or CAML based on event date for "artificial" recurrent items.

**Comment by Jozeevis** [comment]
Yes, that's what I meant @koltyakov, thanks for clarifying.

I read somewhere that it was possible to construct the query in a way that would make Sharepoint return recurrent events as separate items, but I could not figure out how to do it. So if that's not the case I'll simply have to look for another way to handle them, or accept this will be a shortcoming of my implementation.

Thanks for your help!

**Comment by koltyakov** [comment]
In CSOM (C#) there is an option for SPQuery `ExpandRecurrence`.
Also, the projection of the method is in SOAP web service [_vti_bin/Lists.asmx](https://sharepoint.stackexchange.com/questions/128629/does-jsom-offer-an-equivalent-to-spquery-calendardate). Maybe you met these solutions.

Please update this thread if you'll find a reliable way without a necessaty of switching to legacy SOAP for getting recurrent items.

**Comment by patrick-rodgers** [comment]
Thanks @Jozeevis & @koltyakov for the great discussion. I am going to close this as answered, please _reopen_ if you would like to continue the thread. Thanks!
