### ISSUE TITLE
Enhancement - Get List by EntityTypeName

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/PnP-JS-Core#644]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.1]

#### Expected / Desired Behavior / Question

`pnp.sp.web.lists` exposes the functions `getById` and `getByTitle`. To get a list by it's internal name / EntityTypeName you have to filter it yourself, e.g.:

```js
pnp.sp.web.lists.filter("EntityTypeName eq 'MyListName'").get()
.then(result => result[0]) // I'm assuming here that this list exists
.then(listInfo => pnp.sp.web.lists.getById(listInfo.Id))
.then(list => list.items.get())
.then(items => {
  console.log(items)
})
```

It would be great if `lists` exposed a function `getByEntityTypeName` or `getByInternalName` that basically does all this under the hood. So the example above would become:

```js
pnp.sp.web.lists.getByInternalName('MyListName')
.then(list => list.items.get())
.then(items => {
  console.log(items)
})
```

**Comment by koltyakov** [comment]
Hey @johannes-z,

How about `web.getList`?

```TypeScript
pnp.sp.web.getList(`${_spPageContextInfo.webServerRelativeUrl}/Lists/MyListName`)
  .items.get()
  .then(console.log);
```

**Comment by johannes-z** [comment]
Well that does work. I don't think that this is a clean solution though. This way I need to know the exact url where the list/library is located.

**Comment by koltyakov** [comment]
The problem here is that `EntityTypeName` is not unique within a web.
It can easily be the same. Lists can be provisioned to different root folders (not necessarily under /Lists). Document libraries can be created with the same entity type name, even using UI. The situations are quite rare, but Murphy's law is always with us.

Easily reproduced scenario:
- Create a list with the name `TestEntity`
- Rename the list's display name to something user-friendly
- Create a doc lib with the name `TestEntityList`
- Boom! Here we have 2 identical `EntityTypeName`.

I know that it's very unlikely to be repeated, but architecture allows using same `EntityTypeName`s.
We usually include path as an identity to query lists and doc libs to business logic. E.g. `Lists/TestEntity`, then concatenate it with web relative URI.
Ended up that it's the most robust approach years ago.

Ids (guids) - are always different once the solution is reprovisioned, not human readable.
Titles/Display names - can be easily changed by an administrator, leads to logic failing. Also, non-unique on a web.
EntityTypeName - non-unique. Yeah, it's almost never met, but anyway.
List/Lib URI - unique, readable, none changeable with obvious actions. I can't recall a situation when an admin desired to move list from Lists folder to somewhere else, at least without thinking it would break anything. 

As a helper, it can be a web URI combiner method, maybe, e.g.:

```TypeScript
pnp.sp.web.getListByUri('Lists/MyListName') // Imaginary non-existing method
  .items.get().then(console.log);
``` 

which concatenates passed list URI with context's web.
Also, this won't require additional request to the server. Requesting by `EntityTypeName` would always be in one network hope slower.

**Comment by johannes-z** [comment]
Ok I get your point. I never had the case of `EntityTypeName`s not being unique on any shareopint farm, so I guess I didn't consider the possibility. But that wouldn't be too bad either. Instead of a single List/Library you'd get multiple. Isn't that the same case using `lists.getByTitle(...)`? 

The problem about Ids is not that they are not human readable, but that they change if you provision a list to another site collection. 
True, the List/Lib URI is best solution for uniqueness. The problem I see here is that you can't assume that the list is in the root web of a site. A list could easily be moved to a subsite which then would break any links to the list...

Why does `EntityTypeName` need an additional request? It only does so in my example because I wanted to get a types `List` object rather than plain JSON. Requesting a list by `EntityTypeName` gives you all the information about the List you need to create a typed object. It might be slower on the server's side, but that's completely negligible.

**Comment by koltyakov** [comment]
> Isn't that the same case using lists.getByTitle(...)?

This resolves the first occurrence with the provided title. If I'm not wrong.

> The problem about Ids is not that they are not human readable, but that they change if you provision a list to another site collection.

Yes, I mentioned this too in the first place of cons of using Ids.

> The problem I see here is that you can't assume that the list is in the root web of a site

All the methods rely on the web context. getList, getByTitle, getById, web.lists.filter will get only webs on a specified web.
If we need querying lists on other webs we need to specify baseUrl anyway (`let web = new Web('WEB_ABSOLUTE_URL')`). Otherwise, I use search by content types if the data is moved between webs, lists, etc.

> Why does EntityTypeName need an additional request?

As far as I know, there is no endpoint in SharePoint REST to get the list by EntityTypeName (as getByTitle for instance). By requesting lists and filtering them by criteria, then requesting list by Id, for example, two requests are sent physically to the API. At the end of the day, `sp-pnp-js` is just an abstraction layer on top of the REST API. 

In my opinion, helper methods which deal with several physical messages to REST and simplify development experience are great if they are under control and keep the shape of the lib API in elegant condition.

**Comment by patrick-rodgers** [comment]
This appears to be answered with no further action needed so going to close the issue. Please _reopen_ if there is a need to continue the discussion. Thanks!
