### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by brunoferreira2007** [SharePoint/PnP-JS-Core#652]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question  

#### Version

Please specify what version of the library you are using: [   3.0.1      ]

Hi, 
I'm using pnp on an Angular application. Everything working fine util now, that I want to handle some errors. 
I have a simple request to get a table 
` pnp.sp.web.lists.getByTitle("listName").get().then(result => {
      console.log(result)}).catch(error=>{
          console.log(error)
      })`

I saw in another issue #511 , that the error details might come on the property "error.data.responseBody['odata.error'].message.value", the problem is that the value of error.data.responseBody is just "[[body not available]]".

![image](https://user-images.githubusercontent.com/33944868/33509725-0d4fc0f8-d6fc-11e7-9b2e-65750c089fe6.png)

I checked on developer tools, and I see a get request with a 404 response with data in body, but this data is not reflected on pnp catch...

![image](https://user-images.githubusercontent.com/33944868/33509753-3e4fcce8-d6fc-11e7-800a-28c6bf4129e6.png)

**Comment by patrick-rodgers** [comment]
Hi @brunoferreira2007 - I see what you mean, but I am not able to reproduce it myself. What environment are you running in? The library should return an Error object (it is a custom one but inherits from Error) and through the data property you can access whatever was returned by the server as you stated. Let me know and we can try and figure out what might be failing to drop the error handling into the catch block where it creates the body not available message.

You can also [subscribe a logger](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Logging) and you should get a message "There was an error parsing the error response body. See data for details." whose data property will tell you why the parsing failed. If you can do that it would greatly help us troubleshoot. Thanks!

**Comment by brunoferreira2007** [comment]
Hi @patrick-rodgers ,
thanks for the feedback.
I'm running locally a simple Angular CLI application, I have then "sp-rest-proxy" running locally in another port, and I have another proxy on my Angular CLI application, redirecting my requests .../_api to my "sp-rest-proxy" proxy. 
This approach allows me to run the Angular application locally (ng serve) and use pnp like on my Sharepoint evironment directly. 

I have subscribed the logger, with verbose level, and this was my output:
![image](https://user-images.githubusercontent.com/33944868/33690684-a36e5ffc-dadc-11e7-8331-d1edf871d1d9.png)

**Comment by koltyakov** [comment]
This might be a proxy's issue. In any case with the proxy, you should try the same with proxy and on SharePoint page and if the behavior is different it should be fixed in the proxy.
I also tried 404 messaging (but without proxy) and with the same result as Patrick mentioned.
Let's close this one and move the discussion to sp-rest-proxy's issue? Looks like it's not related to PnP JS Core.

**Comment by patrick-rodgers** [comment]
Thanks @brunoferreira2007  for the additional information. I'll be honest I am still unsure based on the data. I have had reports of other weirdness with the angular zone stuff - so will be curious to see what the cause is here.

It may be an issue with the proxy as @koltyakov noted. Let's keep this open because I want to make sure it is fixed but wait for the result of the testing on the issue for the proxy lib.

**Comment by brunoferreira2007** [comment]
After the update provided by @koltyakov  on sp-rest-proxy, the problem was solved

![image](https://user-images.githubusercontent.com/33944868/33723288-31edf440-db64-11e7-8c51-ad14303f0c67.png)

**Comment by patrick-rodgers** [comment]
Awesome, thanks to you both for working through this!
