### ISSUE TITLE
issue Extending with Custom Business Objects

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#698]
#### Category
[ ] Enhancement

[x ] Bug

[x ] Question

#### Version
Hi, I'm trying to use the  feature describe in Extending with Custom Business Objects. My code is
 `private async testmethod():Promise<any>{
    class CustomListItem extends Item{
      Id:number;
      Title:string;
    }
    let listItems:Array<CustomListItem>;
    await pnp.sp.web.lists.getByTitle("CustomList").items.getAs<Array<CustomListItem>>()
    .then(response=>{
      listItems=response;
    });

    for (let listItem of listItems){
      listItem.update({"Title":"NewTitle"})
    }
  }`

I compiles fine but t runtime I am getting an error on the line  that updates the item,. 
Uncaught (in promise) TypeError: listItem.update is not a function

What am I doing wrong here?

**Comment by russgove** [comment]
version is 3.0.4

**Comment by koltyakov** [comment]
Hey Russell,

Didn't get the any bug with the lib. But I can see some issues with the code.

Please check my suggestion:

```typescript
import { List, Item, ItemUpdateResult } from 'sp-pnp-js';

export interface IMyCustomItem {
  Id: number;
  Title: string;
}

export class Test {

  public constructor(private list: List) {}

  public getItems(): Promise<IMyCustomItem[]> {
    return this.list.items
      .select('Id,Title') // Reduces data over wires
      .getAs<IMyCustomItem[]>();
  }

  public async updateAll(items: Item[], payload: any): Promise<ItemUpdateResult[]> {
    let updateResults: ItemUpdateResult[] = [];
    // Sequential async execution
    // In SPO/2016 $batch API is more effective
    for (let item of items) {
      let res = await item.update(payload);
      updateResults.push(res);
    }
    return updateResults;
  }

}
```

`CustomListItem` should not be extended from `Item`. As for me, it looks like an ordinary interface is required here.
 
Generic `getAs<T>` allows binding a specific type for TypeScript to expect returning from the promise.

It's might be a good idea to await inside for/of loop. Otherwise, all the requests will be sent in a time.

**Comment by russgove** [comment]
Thanks andrew. regarding 'CustomListItem should not be extended from Item'.
That is right from the guidance page at
https://github.com/SharePoint/PnP-JS-Core/wiki/Extending-with-Custom-Business-Objects

class MyItem extends Item {
    public Id: number;
    public Title: string;
    public ProductNumber: string;
    public OrderDate: Date;
    public OrderAmount: number;
}

Its no big deal as I have found another way, but perhaps the docs need
to be updated



On Wed, Jan 24, 2018 at 11:11 AM, Andrew Koltyakov <notifications@github.com

**Comment by koltyakov** [comment]
Oops, sorry for the possible confusion.
I meant a bit different thing.
It's possible to extend Item, especially if further chaining of Item's method is required. But not necessarily.

```typescript
class IMyCustomItem extends Item {
  Id: number;
  Title: string;
}
```

is an absolutely correct thing.

So let me correct myself. Your issue was with passing Array as a generic in .getAs<>.
Type error is because Array does not have `update` method. and it should be `.getAs<IMyCustomItem[]>()` where `IMyCustomItem` is really an extension class of Item.

**Comment by russgove** [comment]
Ah, so i just need to use [] instead of Arrayy<> ?

**Comment by koltyakov** [comment]
`getAs<Array>()` => `getAs<CustomListItem[]>(`. Your custom Item class as an array.

**Comment by russgove** [comment]
Awesome! thaks

**Comment by koltyakov** [comment]
Going to close the issue as answered. Feel free to reopen if it won't work for you.
