### ISSUE TITLE
Unable to add a choice field using TypeScript

### ISSUE THREAD

**Issue by bLasTamos** [SharePoint/PnP-JS-Core#704]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.4]

#### Expected / Desired Behavior / Question
The following code should create a choice field:
```typescript
pnp.sp.web.fields.add('name', 'SP.FieldChoice', {
    FieldTypeKind: 6,
    Choices: { results: ['choice1', 'choice2'] }
});
```

#### Observed Behavior
A TypeScript error prevents compilation of the above code. This is due to the type of the 3rd argument of that function, `TypedHash<string | number | boolean>` which prevents me from specifying the choices.

Curiously enough, if you load the library in a browser and use javascript directly, the field is created. In this instance, the type-checking enforced by the TS compiler is getting in the way.

Because this is just a type-checking issue I can totally get around this by casting my properties object to `any` and carry on without type-checking but this simply doesn't make sense.

Thanks!

**Comment by patrick-rodgers** [comment]
We'll have a look. If you have a moment this would be a great opportunity to make the change and submit a PR :)

**Comment by bLasTamos** [comment]
Well I'd actually like to go one step further than that and create strong types for these property objects. It's a lot easier to have vscode tell you what properties you can use when creating a field than just guessing/googling. What do you think?

**Comment by patrick-rodgers** [comment]
If you would like to that would be great. We have been placing large interfaces in the [types](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/types.ts) file. We have typically avoided trying to type out some of these large things because you end up with a huge interface with all optional properties - that doesn't really help you know what you need to use. But having all the property names can't hurt. I've updated the typing to any in #708 to close this issue. If you have the time and want to add additional typing information please do. Thanks!
