### ISSUE TITLE
Get all items/fields from a view

### ISSUE THREAD

**Issue by masterl1983** [SharePoint/PnP-JS-Core#730]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [    latest     ]

#### Expected / Desired Behavior / Question
Hi. I am using a third part library (kendo ui) to display List data in a grid. I am trying to re-use sharepoint standard configurations as much as possible within my custom grid. One of these configurations are views created by user. What would be the preferred way to get all items/fields belonging to a view?

**Comment by patrick-rodgers** [comment]
You can see the [article on views](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Views) to help get you started. The fields in a view can be gotten from the "fields" property from a View instance. There isn't exactly a method to get the items belonging to a view, you could use the "renderAsHtml" method to get the html, but that may not help you as you will get a fully rendered html blob.

If you really just want to show a view you might consider just using something like the OOTB list view web part or the modern equivalent "List". Both allow you to show any of the views from an existing list without having to write any additional code. It also has the benefit of updating if the view updates.

**Comment by masterl1983** [comment]
renderListDataAsStream #665 would be an option but without documentation it is hard to understand how to use it. Any possibilities to build up an example?

**Comment by patrick-rodgers** [comment]
Sure, several folks were working on creating some docs but they didn't complete that work. We can take it as an issue but can't commit to a timeline to create the example.

**Comment by koltyakov** [comment]
`renderListDataAsStream` is used with modern views I would suggest reverse engineering network requests before the documentation is ready.

**Comment by koltyakov** [comment]
Might be useful:

```typescript
(async () => {

  const list = pnp.sp.web.lists.getByTitle('MyList');
  const { HtmlSchemaXml: ViewXml } = await list.defaultView.get();
  const { Row: data } = await list.renderListDataAsStream({
    ViewXml,
    Paging: 'Paged=TRUE&p_ID=48' // skip token here
  });

  console.log(data);

})().catch(console.log);
```

**Comment by patrick-rodgers** [comment]
Ya, like everything this is a time issue for me currently. Would love to get it done which is why I had hopes in that other thread. @masterl1983 - if you had the time and inclination to reverse engineer and document the method that would be great and a big help to the community (and me :)) but for now this isn't something I'll get to in the next few weeks at least.

**Comment by russgove** [comment]
I started trying to document this before but stopped when I ran out of time
and heard that MS was planning on finally documenting the rest api. Here;s
what I got fwiw

The
pnp.sp.web.lists.getByTitle("listname").renderListDataAsStream(renderListDataParameters,overrideParameters)
method can be used instead of the
pnp.sp.web.lists.getByTitle("listname").items.get() when you want to create
a pageable display of list items.

The renderListDataParameters  object  has the following  members:

               ViewXml –  The XML defining the view you want to render
including the ViewFields and Query:

<View><Query></Query><ViewFields><FieldRef Name='Id' /><FieldRef
Name='Title' /></ViewFields> <RowLimit>100</RowLimit

 </View>



               Paging

               FolderServerrelativeUrl

               RenderOptions

                              None – returns the same info as when called
with ListData

                              ContextInfo this results in the call
returning a set of contextual information about the site, the list and the
view.

                              ListData- this results in the call returning
and object which has a ListData object. The ListData object  has an array
called Row that contains the items in the list.the  ListData object  also
has a NextHref (
"?Paged=TRUE&p_ID=30&PageFirstRow=31&View=06cc6c26-778a-4d41-b4ac-bbb682d4479f")
and PrevHref  field used for paging , as well as the has, as well as
FirstRow, Lastrow and RowLimit (provided you specified a RowLimit in your
ViewXML). All of the Lookup columns are automatically expanded. Strangely,
if you pass in a ViewXML to the method the NextHref and PrevHref fields are
not returned in the ListData.

                              ListSchema – this results in the call  returning
and object which has a ListSchema object. The  ListSchema object  includes
an array called Field which defines all of the ViewFields you requested in
the ViewXML of your request, an array of required field names,  information
about a users permissions (used to hide the add item button,  the total
number of items in the view and a slew of other useful information.

menuView

The results from renderListDataAsStream



The fields are returned in a format suitable for display, the dates are
converted to a displayable format, the lookup fields are automatically
expanded.

**Comment by russgove** [comment]
Also, I think only MSFT can really document this. There are a lot of
enums/magic numbers in the API. Kind of hard to decipher if you don't have
the source.

**Comment by koltyakov** [comment]
@phawrylak added nice documentation/extention for `renderListDataAsStream` method https://github.com/SharePoint/PnP-JS-Core/pull/742/files

**Comment by patrick-rodgers** [comment]
Closing this as answered. Please do _reopen_ should you need to continue the conversation. Thanks!

**Comment by patrick-rodgers** [comment]
Docs for renderListDataAsStream  now available at:  https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#working-with-list-items-by-using-rest
