### ISSUE TITLE
How to add/update user field using PnP

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#738]
Hi,
I am working in SharePoint online with PnP JS. How can I add the item with user field and get the item ID after added to the list. Please help me.

Regards,
Philip

**Comment by koltyakov** [comment]
Hey @spvjebaraj,

Check this out - [working user fields](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#user-fields).

When adding items, .add promise returns `ItemAddResult` object. Which consists of `data` (created item metadata, you can find Id in there) and `item` Item object for further chain operations.

![image](https://user-images.githubusercontent.com/7816483/36592694-eca7d8a2-18a7-11e8-92c8-933a3fb04efa.png)

**Comment by spvjebaraj** [comment]
Hi Andrew,
Thanks for share the solution. It is working fine. I used the below method to get the user id by passing email. But I want to get multiple user id by passing multiple emails in one request. Could you please provide the solution for the same.

`return Observable.fromPromise(sp.web.siteUsers.getByEmail(userEmail)
      .get())
      .map(res => {
        return res;
      });`

From the return statement, I am able to get Id property. Please provide the solution. (Here I am using Angular that's why I used Observable.

Thanks,
Philip

**Comment by koltyakov** [comment]
Ensure method resolves a single user.

You can combine:

- Filtering UIL by email
- Ensuring in a batch

for achieving this.

Also, we really appreciate your questions but they are mostly very general and do not relate to the library's issues section rather than "how to do something in REST or JS", I would encourage you targeting such questions in [Tech Community](https://techcommunity.microsoft.com) and leave GitHub issues for issues.

Thanks for understanding!

**Comment by spvjebaraj** [comment]
Hi Andrew,

Thanks for your updates!. I used "forkJoin" method in rxjs operator to handle multiple asynchronous calls and it is worked perfectly. Thanks for your support.

Regards,
Philip
