### ISSUE TITLE
The StaticName and Name do not work on field creation

### ISSUE THREAD

**Issue by PooLP** [SharePoint/PnP-JS-Core#800]
#### Category

[ ] Enhancement

[x] Bug

[x] Question

#### Version

Version : 3.07
SharPoint Online (o365)

#### Expected / Desired Behavior / Question

Hi,
I have a problem to create a fields. The "StaticName" or "Name" for technical name do not work.

If I test this :
```js
var fieldXML = "<Field DisplayName='My PnP TextField' Type='Text' Required='FALSE' StaticName='myPnpTecnicalName' />";
 
$pnp.sp.web.lists.getByTitle('my list').fields.createFieldAsXml(fieldXML).then(function(result) {
	console.log(result); 
});
```
The "DisplayName" is always used, never the "StaticName" or "Name" parameters. I can not differentiate the displayed name (DisplayName) from the technical name (StaticName or Name) It's normal ? I never had the problem in xml (declarative mode in visual studio (.wsp))

Thanks,
Richard

**Comment by russgove** [comment]
I always set both StaticName and Name.  If you set bolth, then that becomes
the internal name

**Comment by PooLP** [comment]
In new test, it's only DisplayName becomes the internal name

```js
var fieldXML = "<Field Type='Text' Required='FALSE' StaticName='myPnpTecnicalName' Name='myPnpTecnicalName' DisplayName='My name to displayed' />";
 
$pnp.sp.web.lists.getByTitle('My List').fields.createFieldAsXml(fieldXML).then(function(result) {
	console.log(result); 
});
```
![pnp](https://user-images.githubusercontent.com/582733/39582245-d1cce3e8-4eed-11e8-9267-a649a738b145.jpg)

**Comment by koltyakov** [comment]
Hey guys,

It's not something which can be fixed in the library. Requests are transmitted to SP REST API without changes which can potentially introduce this issue. In other words, raw REST request will behave the same.

AFAIK, REST API ignores StaticName/Name in field schema XML when creating a field in a list directly. At the same time, the same schema will end up with what you expect when creating a site column.

What I would suggest here is create a field with display name equal to the desired InternalName, then send an update of the field name to the desired display name.

P.S.

Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please reopen if you need to continue the discussion.
